version: "3.8"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: redash
      POSTGRES_PASSWORD: redash
      POSTGRES_DB: redash
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: always

  redash-base:
    image: redash/redash:10.1.0.b50633
    build:
      context: .
      dockerfile: Dockerfile.redash
    environment:
      REDASH_DATABASE_URL: postgresql://redash:redash@postgres:5432/redash
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
      REDASH_LOG_LEVEL: DEBUG
    depends_on:
      - postgres
      - redis

  server:
    extends:
      service: redash-base
    command: server
    ports:
      - "5000:5000"

  scheduler:
    extends:
      service: redash-base
    command: scheduler

  worker:
    extends:
      service: redash-base
    command: worker

volumes:
  postgres_data:
